// import 'package:flutter/material.dart';
// import 'package:intl_phone_number_input/intl_phone_number_input.dart';
// import 'package:get/get.dart';
// import '../../controllers/auth/auth_phone_controller.dart';
// import 'code_verification_screen.dart';

// class PhoneNumberScreen extends StatefulWidget {
//   const PhoneNumberScreen({super.key});

//   @override
//   State<PhoneNumberScreen> createState() => _PhoneNumberScreenState();
// }

// class _PhoneNumberScreenState extends State<PhoneNumberScreen> {
//   final AuthPhoneController _authPhoneController =
//       Get.find<AuthPhoneController>();
//   final TextEditingController _phoneController = TextEditingController();
//   PhoneNumber _phoneNumber =
//       PhoneNumber(isoCode: 'CD'); // Congo (Brazzaville) comme pays par défaut

//   final List<String> countries = [
//     'AD',
//     'AE',
//     'AF',
//     'AG',
//     'AI',
//     'AL',
//     'AM',
//     'AO',
//     'AR',
//     'AS',
//     'AT',
//     'AU',
//     'AW',
//     'AX',
//     'AZ',
//     'BA',
//     'BB',
//     'BD',
//     'BE',
//     'BF',
//     'BG',
//     'BH',
//     'BI',
//     'BJ',
//     'BL',
//     'BM',
//     'BN',
//     'BO',
//     'BQ',
//     'BR',
//     'BS',
//     'BT',
//     'BV',
//     'BW',
//     'BY',
//     'BZ',
//     'CA',
//     'CC',
//     'CD',
//     'CF',
//     'CG',
//     'CH',
//     'CI',
//     'CK',
//     'CL',
//     'CM',
//     'CN',
//     'CO',
//     'CR',
//     'CU',
//     'CV',
//     'CW',
//     'CX',
//     'CY',
//     'CZ',
//     'DE',
//     'DJ',
//     'DK',
//     'DM',
//     'DO',
//     'DZ',
//     'EC',
//     'EE',
//     'EG',
//     'EH',
//     'ER',
//     'ES',
//     'ET',
//     'FI',
//     'FJ',
//     'FM',
//     'FO',
//     'FR',
//     'GA',
//     'GB',
//     'GD',
//     'GE',
//     'GF',
//     'GG',
//     'GH',
//     'GI',
//     'GL',
//     'GM',
//     'GN',
//     'GP',
//     'GQ',
//     'GR',
//     'GT',
//     'GU',
//     'GW',
//     'GY',
//     'HK',
//     'HM',
//     'HN',
//     'HR',
//     'HT',
//     'HU',
//     'ID',
//     'IE',
//     'IL',
//     'IM',
//     'IN',
//     'IO',
//     'IQ',
//     'IR',
//     'IS',
//     'IT',
//     'JE',
//     'JM',
//     'JO',
//     'JP',
//     'KE',
//     'KG',
//     'KH',
//     'KI',
//     'KM',
//     'KN',
//     'KP',
//     'KR',
//     'KW',
//     'KY',
//     'KZ',
//     'LA',
//     'LB',
//     'LC',
//     'LI',
//     'LK',
//     'LR',
//     'LS',
//     'LT',
//     'LU',
//     'LV',
//     'LY',
//     'MA',
//     'MC',
//     'MD',
//     'ME',
//     'MF',
//     'MG',
//     'MH',
//     'MK',
//     'ML',
//     'MM',
//     'MN',
//     'MO',
//     'MP',
//     'MQ',
//     'MR',
//     'MS',
//     'MT',
//     'MU',
//     'MV',
//     'MW',
//     'MX',
//     'MY',
//     'MZ',
//     'NA',
//     'NC',
//     'NE',
//     'NF',
//     'NG',
//     'NI',
//     'NL',
//     'NO',
//     'NP',
//     'NR',
//     'NU',
//     'NZ',
//     'OM',
//     'PA',
//     'PE',
//     'PF',
//     'PG',
//     'PH',
//     'PK',
//     'PL',
//     'PM',
//     'PN',
//     'PR',
//     'PT',
//     'PW',
//     'PY',
//     'QA',
//     'RE',
//     'RO',
//     'RS',
//     'RU',
//     'RW',
//     'SA',
//     'SB',
//     'SC',
//     'SD',
//     'SE',
//     'SG',
//     'SH',
//     'SI',
//     'SJ',
//     'SK',
//     'SL',
//     'SM',
//     'SN',
//     'SO',
//     'SR',
//     'SS',
//     'ST',
//     'SV',
//     'SX',
//     'SY',
//     'SZ',
//     'TC',
//     'TD',
//     'TF',
//     'TG',
//     'TH',
//     'TJ',
//     'TK',
//     'TL',
//     'TM',
//     'TN',
//     'TO',
//     'TR',
//     'TT',
//     'TV',
//     'TZ',
//     'UA',
//     'UG',
//     'UM',
//     'US',
//     'UY',
//     'UZ',
//     'VA',
//     'VC',
//     'VE',
//     'VG',
//     'VI',
//     'VN',
//     'VU',
//     'WF',
//     'WS',
//     'YE',
//     'YT',
//     'ZA',
//     'ZM',
//     'ZW',
//   ];

//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       appBar: AppBar(title: const Text('Numéro de Téléphone')),
//       body: Padding(
//         padding: const EdgeInsets.all(16.0),
//         child: Column(
//           mainAxisAlignment: MainAxisAlignment.center,
//           children: [
//             InternationalPhoneNumberInput(
//               onInputChanged: (PhoneNumber number) {
//                 _phoneNumber = number;
//               },
//               initialValue: _phoneNumber,
//               textFieldController: _phoneController,
//               formatInput: false,
//               inputBorder: OutlineInputBorder(),
//               selectorConfig: SelectorConfig(
//                 selectorType: PhoneInputSelectorType.DIALOG,
//               ),
//               ignoreBlank: false,
//               autoValidateMode: AutovalidateMode.onUserInteraction,
//               selectorTextStyle: const TextStyle(color: Colors.black),
//               textStyle: const TextStyle(color: Colors.black),
//               cursorColor: Colors.blue,
//               countries: countries, // Liste complète des pays
//               inputDecoration: const InputDecoration(
//                 labelText: 'Numéro de téléphone',
//                 border: OutlineInputBorder(),
//               ),
//             ),
//             const SizedBox(height: 20),
//             Obx(() {
//               if (_authPhoneController.isCodeSent.value) {
//                 return ElevatedButton(
//                   onPressed: () {
//                     Get.to(() => CodeVerificationScreen(
//                           verificationId:
//                               _authPhoneController.verificationId.value,
//                         ));
//                   },
//                   child: const Text('Vérifier le code'),
//                 );
//               } else {
//                 return ElevatedButton(
//                   onPressed: () {
//                     _authPhoneController
//                         .sendCode(_phoneNumber.phoneNumber ?? '');
//                   },
//                   child: const Text('Envoyer le code'),
//                 );
//               }
//             }),
//           ],
//         ),
//       ),
//     );
//   }
// }
